FROM debian:stretch

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y \
    software-properties-common \
    python-pip \
    git \
 && rm -rf /var/lib/apt/lists/*

RUN pip install ansible

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
