FROM debian:wheezy

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y --no-install-recommends  \
    software-properties-common \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    git \
 && rm -rf /var/lib/apt/lists/*

RUN pip install ansible

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
